create table playerGameStats (
  gameId                  bigint not NULL,
  teamId                  bigint not NULL,
  playerId                bigint default NULL,
  goals                   int default 0,
  substitutionQuarter1    int default 0,
  substitutionQuarter2    int default 0,
  substitutionQuarter3    int default 0,
  substitutionQuarter4    int default 0,
  keeperQuarter1          int default 0,
  keeperQuarter2          int default 0,
  keeperQuarter3          int default 0,
  keeperQuarter4          int default 0,
  injuredQuarter1         int default 0,
  injuredQuarter2         int default 0,
  injuredQuarter3         int default 0,
  injuredQuarter4         int default 0,
  absentQuarter1          int default 0,
  absentQuarter2          int default 0,
  absentQuarter3          int default 0,
  absentQuarter4          int default 0,
  yellowCards             int default 0,
  redCard                 int default 0,

  PRIMARY KEY (gameId, teamId, playerId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;